FROM node:latest as node
WORKDIR /app
COPY . .
RUN npm install
RUN npm install -g @angular/cli@9.0.3
RUN npm config set unsafe-perm true
RUN npm run build --prod

FROM nginx:alpine
COPY --from=node /app/dist/swe645-app /usr/share/nginx/html